// Generated by Bisonc++ V4.13.01 on Mon, 17 Dec 2018 07:35:48 +0100

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {314, 1}, // 1: start ->  members
     {315, 0}, // 2: members ->  <empty>
     {315, 2}, // 3: members ->  function members
     {315, 3}, // 4: members (SEMICOLON) ->  declaration SEMICOLON members
     {316, 9}, // 5: function (IDENTIFIER) ->  type IDENTIFIER OPEN parameterlist CLOSE BOPEN declarations statements BCLOSE
     {317, 0}, // 6: parameterlist ->  <empty>
     {317, 1}, // 7: parameterlist ->  parameters
     {318, 1}, // 8: parameters ->  declaration
     {318, 3}, // 9: parameters (COMMA) ->  declaration COMMA parameters
     {319, 0}, // 10: declarations ->  <empty>
     {319, 3}, // 11: declarations (SEMICOLON) ->  declaration SEMICOLON declarations
     {320, 2}, // 12: declaration (IDENTIFIER) ->  type IDENTIFIER
     {321, 1}, // 13: type (UNSIGNED) ->  UNSIGNED
     {321, 1}, // 14: type (BOOL) ->  BOOL
     {322, 0}, // 15: statements ->  <empty>
     {322, 2}, // 16: statements ->  statement statements
     {323, 1}, // 17: statement ->  assignment
     {323, 1}, // 18: statement ->  read
     {323, 1}, // 19: statement ->  write
     {323, 1}, // 20: statement ->  exprStatement
     {323, 1}, // 21: statement ->  return
     {323, 1}, // 22: statement ->  break
     {323, 1}, // 23: statement ->  if
     {323, 1}, // 24: statement ->  while
     {324, 4}, // 25: assignment (IDENTIFIER) ->  IDENTIFIER ASSIGN expr SEMICOLON
     {325, 4}, // 26: read (CIN) ->  CIN READ IDENTIFIER SEMICOLON
     {326, 4}, // 27: write (COUT) ->  COUT WRITE expr SEMICOLON
     {327, 2}, // 28: exprStatement (SEMICOLON) ->  expr SEMICOLON
     {328, 3}, // 29: return (RETURN) ->  RETURN expr SEMICOLON
     {329, 2}, // 30: break (BREAK) ->  BREAK SEMICOLON
     {330, 11}, // 31: if (IF) ->  IF OPEN expr CLOSE BOPEN statements BCLOSE ELSE BOPEN statements BCLOSE
     {330, 7}, // 32: if (IF) ->  IF OPEN expr CLOSE BOPEN statements BCLOSE
     {331, 7}, // 33: while (WHILE) ->  WHILE OPEN expr CLOSE BOPEN statements BCLOSE
     {332, 1}, // 34: expr (FALSE) ->  FALSE
     {332, 1}, // 35: expr (TRUE) ->  TRUE
     {332, 1}, // 36: expr (NUMBER) ->  NUMBER
     {332, 4}, // 37: expr (IDENTIFIER) ->  IDENTIFIER OPEN argumentlist CLOSE
     {332, 1}, // 38: expr (IDENTIFIER) ->  IDENTIFIER
     {332, 3}, // 39: expr (PLUS) ->  expr PLUS expr
     {332, 3}, // 40: expr (MINUS) ->  expr MINUS expr
     {332, 3}, // 41: expr (MUL) ->  expr MUL expr
     {332, 3}, // 42: expr (DIV) ->  expr DIV expr
     {332, 3}, // 43: expr (MOD) ->  expr MOD expr
     {332, 3}, // 44: expr (EQUAL) ->  expr EQUAL expr
     {332, 3}, // 45: expr (NOT_EQUAL) ->  expr NOT_EQUAL expr
     {332, 3}, // 46: expr (LESS) ->  expr LESS expr
     {332, 3}, // 47: expr (LESS_EQUAL) ->  expr LESS_EQUAL expr
     {332, 3}, // 48: expr (GREATER) ->  expr GREATER expr
     {332, 3}, // 49: expr (GREATER_EQUAL) ->  expr GREATER_EQUAL expr
     {332, 3}, // 50: expr (AND) ->  expr AND expr
     {332, 3}, // 51: expr (OR) ->  expr OR expr
     {332, 2}, // 52: expr (NEGATE) ->  NEGATE expr
     {332, 3}, // 53: expr (OPEN) ->  OPEN expr CLOSE
     {333, 0}, // 54: argumentlist ->  <empty>
     {333, 1}, // 55: argumentlist ->  arguments
     {334, 1}, // 56: arguments ->  expr
     {334, 3}, // 57: arguments (COMMA) ->  arguments COMMA expr
     {335, 1}, // 58: start_$ ->  start
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_DEF}, {  8} },               
    { {     314}, {  1} }, // start      
    { {     315}, {  2} }, // members    
    { {     316}, {  3} }, // function   
    { {     320}, {  4} }, // declaration
    { {     321}, {  5} }, // type       
    { {     290}, {  6} }, // UNSIGNED   
    { {     291}, {  7} }, // BOOL       
    { {       0}, { -2} },               
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_3[] =
{
    { { REQ_DEF}, {  7} },               
    { {     315}, {  8} }, // members    
    { {     316}, {  3} }, // function   
    { {     320}, {  4} }, // declaration
    { {     321}, {  5} }, // type       
    { {     290}, {  6} }, // UNSIGNED   
    { {     291}, {  7} }, // BOOL       
    { {       0}, { -2} },               
};

SR__ s_4[] =
{
    { { REQ_TOKEN}, { 2} },             
    { {       278}, { 9} }, // SEMICOLON
    { {         0}, { 0} },             
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       280}, { 10} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_6[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_7[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_8[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_9[] =
{
    { { REQ_DEF}, {  7} },               
    { {     315}, { 11} }, // members    
    { {     316}, {  3} }, // function   
    { {     320}, {  4} }, // declaration
    { {     321}, {  5} }, // type       
    { {     290}, {  6} }, // UNSIGNED   
    { {     291}, {  7} }, // BOOL       
    { {       0}, { -2} },               
};

SR__ s_10[] =
{
    { { REQ_DEF}, {   2} },        
    { {     271}, {  12} }, // OPEN
    { {       0}, { -12} },        
};

SR__ s_11[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_12[] =
{
    { { REQ_DEF}, {  7} },                 
    { {     317}, { 13} }, // parameterlist
    { {     318}, { 14} }, // parameters   
    { {     320}, { 15} }, // declaration  
    { {     321}, { 16} }, // type         
    { {     290}, {  6} }, // UNSIGNED     
    { {     291}, {  7} }, // BOOL         
    { {       0}, { -6} },                 
};

SR__ s_13[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       272}, { 17} }, // CLOSE
    { {         0}, {  0} },         
};

SR__ s_14[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_15[] =
{
    { { REQ_DEF}, {  2} },         
    { {     279}, { 18} }, // COMMA
    { {       0}, { -8} },         
};

SR__ s_16[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       280}, { 19} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_17[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       276}, { 20} }, // BOPEN
    { {         0}, {  0} },         
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  6} },               
    { {       318}, { 21} }, // parameters 
    { {       320}, { 15} }, // declaration
    { {       321}, { 16} }, // type       
    { {       290}, {  6} }, // UNSIGNED   
    { {       291}, {  7} }, // BOOL       
    { {         0}, {  0} },               
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_20[] =
{
    { { REQ_DEF}, {   6} },                
    { {     319}, {  22} }, // declarations
    { {     320}, {  23} }, // declaration 
    { {     321}, {  16} }, // type        
    { {     290}, {   6} }, // UNSIGNED    
    { {     291}, {   7} }, // BOOL        
    { {       0}, { -10} },                
};

SR__ s_21[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_22[] =
{
    { { REQ_DEF}, {  24} },                 
    { {     322}, {  24} }, // statements   
    { {     323}, {  25} }, // statement    
    { {     324}, {  26} }, // assignment   
    { {     325}, {  27} }, // read         
    { {     326}, {  28} }, // write        
    { {     327}, {  29} }, // exprStatement
    { {     328}, {  30} }, // return       
    { {     329}, {  31} }, // break        
    { {     330}, {  32} }, // if           
    { {     331}, {  33} }, // while        
    { {     280}, {  34} }, // IDENTIFIER   
    { {     287}, {  35} }, // CIN          
    { {     286}, {  36} }, // COUT         
    { {     332}, {  37} }, // expr         
    { {     288}, {  38} }, // RETURN       
    { {     289}, {  39} }, // BREAK        
    { {     283}, {  40} }, // IF           
    { {     285}, {  41} }, // WHILE        
    { {     282}, {  42} }, // FALSE        
    { {     281}, {  43} }, // TRUE         
    { {     292}, {  44} }, // NUMBER       
    { {     270}, {  45} }, // NEGATE       
    { {     271}, {  46} }, // OPEN         
    { {       0}, { -15} },                 
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       278}, { 47} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       277}, { 48} }, // BCLOSE
    { {         0}, {  0} },          
};

SR__ s_25[] =
{
    { { REQ_DEF}, {  24} },                 
    { {     322}, {  49} }, // statements   
    { {     323}, {  25} }, // statement    
    { {     324}, {  26} }, // assignment   
    { {     325}, {  27} }, // read         
    { {     326}, {  28} }, // write        
    { {     327}, {  29} }, // exprStatement
    { {     328}, {  30} }, // return       
    { {     329}, {  31} }, // break        
    { {     330}, {  32} }, // if           
    { {     331}, {  33} }, // while        
    { {     280}, {  34} }, // IDENTIFIER   
    { {     287}, {  35} }, // CIN          
    { {     286}, {  36} }, // COUT         
    { {     332}, {  37} }, // expr         
    { {     288}, {  38} }, // RETURN       
    { {     289}, {  39} }, // BREAK        
    { {     283}, {  40} }, // IF           
    { {     285}, {  41} }, // WHILE        
    { {     282}, {  42} }, // FALSE        
    { {     281}, {  43} }, // TRUE         
    { {     292}, {  44} }, // NUMBER       
    { {     270}, {  45} }, // NEGATE       
    { {     271}, {  46} }, // OPEN         
    { {       0}, { -15} },                 
};

SR__ s_26[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_27[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_28[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_29[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_30[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_31[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_32[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_34[] =
{
    { { REQ_DEF}, {   3} },          
    { {     273}, {  50} }, // ASSIGN
    { {     271}, {  51} }, // OPEN  
    { {       0}, { -38} },          
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       274}, { 52} }, // READ
    { {         0}, {  0} },        
};

SR__ s_36[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       275}, { 53} }, // WRITE
    { {         0}, {  0} },         
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, { 15} },                 
    { {       278}, { 54} }, // SEMICOLON    
    { {       265}, { 55} }, // PLUS         
    { {       266}, { 56} }, // MINUS        
    { {       267}, { 57} }, // MUL          
    { {       268}, { 58} }, // DIV          
    { {       269}, { 59} }, // MOD          
    { {       259}, { 60} }, // EQUAL        
    { {       260}, { 61} }, // NOT_EQUAL    
    { {       261}, { 62} }, // LESS         
    { {       263}, { 63} }, // LESS_EQUAL   
    { {       262}, { 64} }, // GREATER      
    { {       264}, { 65} }, // GREATER_EQUAL
    { {       257}, { 66} }, // AND          
    { {       258}, { 67} }, // OR           
    { {         0}, {  0} },                 
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       332}, { 68} }, // expr      
    { {       282}, { 42} }, // FALSE     
    { {       281}, { 43} }, // TRUE      
    { {       292}, { 44} }, // NUMBER    
    { {       280}, { 69} }, // IDENTIFIER
    { {       270}, { 45} }, // NEGATE    
    { {       271}, { 46} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       278}, { 70} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       271}, { 71} }, // OPEN
    { {         0}, {  0} },        
};

SR__ s_41[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       271}, { 72} }, // OPEN
    { {         0}, {  0} },        
};

SR__ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_43[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_44[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       332}, { 73} }, // expr      
    { {       282}, { 42} }, // FALSE     
    { {       281}, { 43} }, // TRUE      
    { {       292}, { 44} }, // NUMBER    
    { {       280}, { 69} }, // IDENTIFIER
    { {       270}, { 45} }, // NEGATE    
    { {       271}, { 46} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       332}, { 74} }, // expr      
    { {       282}, { 42} }, // FALSE     
    { {       281}, { 43} }, // TRUE      
    { {       292}, { 44} }, // NUMBER    
    { {       280}, { 69} }, // IDENTIFIER
    { {       270}, { 45} }, // NEGATE    
    { {       271}, { 46} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_47[] =
{
    { { REQ_DEF}, {   6} },                
    { {     319}, {  75} }, // declarations
    { {     320}, {  23} }, // declaration 
    { {     321}, {  16} }, // type        
    { {     290}, {   6} }, // UNSIGNED    
    { {     291}, {   7} }, // BOOL        
    { {       0}, { -10} },                
};

SR__ s_48[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_49[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       332}, { 76} }, // expr      
    { {       282}, { 42} }, // FALSE     
    { {       281}, { 43} }, // TRUE      
    { {       292}, { 44} }, // NUMBER    
    { {       280}, { 69} }, // IDENTIFIER
    { {       270}, { 45} }, // NEGATE    
    { {       271}, { 46} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_51[] =
{
    { { REQ_DEF}, {  10} },                
    { {     333}, {  77} }, // argumentlist
    { {     334}, {  78} }, // arguments   
    { {     332}, {  79} }, // expr        
    { {     282}, {  42} }, // FALSE       
    { {     281}, {  43} }, // TRUE        
    { {     292}, {  44} }, // NUMBER      
    { {     280}, {  69} }, // IDENTIFIER  
    { {     270}, {  45} }, // NEGATE      
    { {     271}, {  46} }, // OPEN        
    { {       0}, { -54} },                
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       280}, { 80} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       332}, { 81} }, // expr      
    { {       282}, { 42} }, // FALSE     
    { {       281}, { 43} }, // TRUE      
    { {       292}, { 44} }, // NUMBER    
    { {       280}, { 69} }, // IDENTIFIER
    { {       270}, { 45} }, // NEGATE    
    { {       271}, { 46} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_54[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       332}, { 82} }, // expr      
    { {       282}, { 42} }, // FALSE     
    { {       281}, { 43} }, // TRUE      
    { {       292}, { 44} }, // NUMBER    
    { {       280}, { 69} }, // IDENTIFIER
    { {       270}, { 45} }, // NEGATE    
    { {       271}, { 46} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       332}, { 83} }, // expr      
    { {       282}, { 42} }, // FALSE     
    { {       281}, { 43} }, // TRUE      
    { {       292}, { 44} }, // NUMBER    
    { {       280}, { 69} }, // IDENTIFIER
    { {       270}, { 45} }, // NEGATE    
    { {       271}, { 46} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       332}, { 84} }, // expr      
    { {       282}, { 42} }, // FALSE     
    { {       281}, { 43} }, // TRUE      
    { {       292}, { 44} }, // NUMBER    
    { {       280}, { 69} }, // IDENTIFIER
    { {       270}, { 45} }, // NEGATE    
    { {       271}, { 46} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       332}, { 85} }, // expr      
    { {       282}, { 42} }, // FALSE     
    { {       281}, { 43} }, // TRUE      
    { {       292}, { 44} }, // NUMBER    
    { {       280}, { 69} }, // IDENTIFIER
    { {       270}, { 45} }, // NEGATE    
    { {       271}, { 46} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       332}, { 86} }, // expr      
    { {       282}, { 42} }, // FALSE     
    { {       281}, { 43} }, // TRUE      
    { {       292}, { 44} }, // NUMBER    
    { {       280}, { 69} }, // IDENTIFIER
    { {       270}, { 45} }, // NEGATE    
    { {       271}, { 46} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       332}, { 87} }, // expr      
    { {       282}, { 42} }, // FALSE     
    { {       281}, { 43} }, // TRUE      
    { {       292}, { 44} }, // NUMBER    
    { {       280}, { 69} }, // IDENTIFIER
    { {       270}, { 45} }, // NEGATE    
    { {       271}, { 46} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       332}, { 88} }, // expr      
    { {       282}, { 42} }, // FALSE     
    { {       281}, { 43} }, // TRUE      
    { {       292}, { 44} }, // NUMBER    
    { {       280}, { 69} }, // IDENTIFIER
    { {       270}, { 45} }, // NEGATE    
    { {       271}, { 46} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       332}, { 89} }, // expr      
    { {       282}, { 42} }, // FALSE     
    { {       281}, { 43} }, // TRUE      
    { {       292}, { 44} }, // NUMBER    
    { {       280}, { 69} }, // IDENTIFIER
    { {       270}, { 45} }, // NEGATE    
    { {       271}, { 46} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       332}, { 90} }, // expr      
    { {       282}, { 42} }, // FALSE     
    { {       281}, { 43} }, // TRUE      
    { {       292}, { 44} }, // NUMBER    
    { {       280}, { 69} }, // IDENTIFIER
    { {       270}, { 45} }, // NEGATE    
    { {       271}, { 46} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       332}, { 91} }, // expr      
    { {       282}, { 42} }, // FALSE     
    { {       281}, { 43} }, // TRUE      
    { {       292}, { 44} }, // NUMBER    
    { {       280}, { 69} }, // IDENTIFIER
    { {       270}, { 45} }, // NEGATE    
    { {       271}, { 46} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       332}, { 92} }, // expr      
    { {       282}, { 42} }, // FALSE     
    { {       281}, { 43} }, // TRUE      
    { {       292}, { 44} }, // NUMBER    
    { {       280}, { 69} }, // IDENTIFIER
    { {       270}, { 45} }, // NEGATE    
    { {       271}, { 46} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       332}, { 93} }, // expr      
    { {       282}, { 42} }, // FALSE     
    { {       281}, { 43} }, // TRUE      
    { {       292}, { 44} }, // NUMBER    
    { {       280}, { 69} }, // IDENTIFIER
    { {       270}, { 45} }, // NEGATE    
    { {       271}, { 46} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       332}, { 94} }, // expr      
    { {       282}, { 42} }, // FALSE     
    { {       281}, { 43} }, // TRUE      
    { {       292}, { 44} }, // NUMBER    
    { {       280}, { 69} }, // IDENTIFIER
    { {       270}, { 45} }, // NEGATE    
    { {       271}, { 46} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_68[] =
{
    { { REQ_TOKEN}, { 15} },                 
    { {       278}, { 95} }, // SEMICOLON    
    { {       265}, { 55} }, // PLUS         
    { {       266}, { 56} }, // MINUS        
    { {       267}, { 57} }, // MUL          
    { {       268}, { 58} }, // DIV          
    { {       269}, { 59} }, // MOD          
    { {       259}, { 60} }, // EQUAL        
    { {       260}, { 61} }, // NOT_EQUAL    
    { {       261}, { 62} }, // LESS         
    { {       263}, { 63} }, // LESS_EQUAL   
    { {       262}, { 64} }, // GREATER      
    { {       264}, { 65} }, // GREATER_EQUAL
    { {       257}, { 66} }, // AND          
    { {       258}, { 67} }, // OR           
    { {         0}, {  0} },                 
};

SR__ s_69[] =
{
    { { REQ_DEF}, {   2} },        
    { {     271}, {  51} }, // OPEN
    { {       0}, { -38} },        
};

SR__ s_70[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_71[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       332}, { 96} }, // expr      
    { {       282}, { 42} }, // FALSE     
    { {       281}, { 43} }, // TRUE      
    { {       292}, { 44} }, // NUMBER    
    { {       280}, { 69} }, // IDENTIFIER
    { {       270}, { 45} }, // NEGATE    
    { {       271}, { 46} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_72[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       332}, { 97} }, // expr      
    { {       282}, { 42} }, // FALSE     
    { {       281}, { 43} }, // TRUE      
    { {       292}, { 44} }, // NUMBER    
    { {       280}, { 69} }, // IDENTIFIER
    { {       270}, { 45} }, // NEGATE    
    { {       271}, { 46} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_73[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_74[] =
{
    { { REQ_TOKEN}, { 15} },                 
    { {       272}, { 98} }, // CLOSE        
    { {       265}, { 55} }, // PLUS         
    { {       266}, { 56} }, // MINUS        
    { {       267}, { 57} }, // MUL          
    { {       268}, { 58} }, // DIV          
    { {       269}, { 59} }, // MOD          
    { {       259}, { 60} }, // EQUAL        
    { {       260}, { 61} }, // NOT_EQUAL    
    { {       261}, { 62} }, // LESS         
    { {       263}, { 63} }, // LESS_EQUAL   
    { {       262}, { 64} }, // GREATER      
    { {       264}, { 65} }, // GREATER_EQUAL
    { {       257}, { 66} }, // AND          
    { {       258}, { 67} }, // OR           
    { {         0}, {  0} },                 
};

SR__ s_75[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, { 15} },                 
    { {       278}, { 99} }, // SEMICOLON    
    { {       265}, { 55} }, // PLUS         
    { {       266}, { 56} }, // MINUS        
    { {       267}, { 57} }, // MUL          
    { {       268}, { 58} }, // DIV          
    { {       269}, { 59} }, // MOD          
    { {       259}, { 60} }, // EQUAL        
    { {       260}, { 61} }, // NOT_EQUAL    
    { {       261}, { 62} }, // LESS         
    { {       263}, { 63} }, // LESS_EQUAL   
    { {       262}, { 64} }, // GREATER      
    { {       264}, { 65} }, // GREATER_EQUAL
    { {       257}, { 66} }, // AND          
    { {       258}, { 67} }, // OR           
    { {         0}, {  0} },                 
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, {   2} },         
    { {       272}, { 100} }, // CLOSE
    { {         0}, {   0} },         
};

SR__ s_78[] =
{
    { { REQ_DEF}, {   2} },         
    { {     279}, { 101} }, // COMMA
    { {       0}, { -55} },         
};

SR__ s_79[] =
{
    { { REQ_DEF}, {  14} },                 
    { {     265}, {  55} }, // PLUS         
    { {     266}, {  56} }, // MINUS        
    { {     267}, {  57} }, // MUL          
    { {     268}, {  58} }, // DIV          
    { {     269}, {  59} }, // MOD          
    { {     259}, {  60} }, // EQUAL        
    { {     260}, {  61} }, // NOT_EQUAL    
    { {     261}, {  62} }, // LESS         
    { {     263}, {  63} }, // LESS_EQUAL   
    { {     262}, {  64} }, // GREATER      
    { {     264}, {  65} }, // GREATER_EQUAL
    { {     257}, {  66} }, // AND          
    { {     258}, {  67} }, // OR           
    { {       0}, { -56} },                 
};

SR__ s_80[] =
{
    { { REQ_TOKEN}, {   2} },             
    { {       278}, { 102} }, // SEMICOLON
    { {         0}, {   0} },             
};

SR__ s_81[] =
{
    { { REQ_TOKEN}, {  15} },                 
    { {       278}, { 103} }, // SEMICOLON    
    { {       265}, {  55} }, // PLUS         
    { {       266}, {  56} }, // MINUS        
    { {       267}, {  57} }, // MUL          
    { {       268}, {  58} }, // DIV          
    { {       269}, {  59} }, // MOD          
    { {       259}, {  60} }, // EQUAL        
    { {       260}, {  61} }, // NOT_EQUAL    
    { {       261}, {  62} }, // LESS         
    { {       263}, {  63} }, // LESS_EQUAL   
    { {       262}, {  64} }, // GREATER      
    { {       264}, {  65} }, // GREATER_EQUAL
    { {       257}, {  66} }, // AND          
    { {       258}, {  67} }, // OR           
    { {         0}, {   0} },                 
};

SR__ s_82[] =
{
    { { REQ_DEF}, {   4} },       
    { {     267}, {  57} }, // MUL
    { {     268}, {  58} }, // DIV
    { {     269}, {  59} }, // MOD
    { {       0}, { -39} },       
};

SR__ s_83[] =
{
    { { REQ_DEF}, {   4} },       
    { {     267}, {  57} }, // MUL
    { {     268}, {  58} }, // DIV
    { {     269}, {  59} }, // MOD
    { {       0}, { -40} },       
};

SR__ s_84[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_85[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_86[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_87[] =
{
    { { REQ_DEF}, {  10} },                 
    { {     265}, {  55} }, // PLUS         
    { {     266}, {  56} }, // MINUS        
    { {     267}, {  57} }, // MUL          
    { {     268}, {  58} }, // DIV          
    { {     269}, {  59} }, // MOD          
    { {     261}, {  62} }, // LESS         
    { {     263}, {  63} }, // LESS_EQUAL   
    { {     262}, {  64} }, // GREATER      
    { {     264}, {  65} }, // GREATER_EQUAL
    { {       0}, { -44} },                 
};

SR__ s_88[] =
{
    { { REQ_DEF}, {  10} },                 
    { {     265}, {  55} }, // PLUS         
    { {     266}, {  56} }, // MINUS        
    { {     267}, {  57} }, // MUL          
    { {     268}, {  58} }, // DIV          
    { {     269}, {  59} }, // MOD          
    { {     261}, {  62} }, // LESS         
    { {     263}, {  63} }, // LESS_EQUAL   
    { {     262}, {  64} }, // GREATER      
    { {     264}, {  65} }, // GREATER_EQUAL
    { {       0}, { -45} },                 
};

SR__ s_89[] =
{
    { { REQ_DEF}, {   6} },         
    { {     265}, {  55} }, // PLUS 
    { {     266}, {  56} }, // MINUS
    { {     267}, {  57} }, // MUL  
    { {     268}, {  58} }, // DIV  
    { {     269}, {  59} }, // MOD  
    { {       0}, { -46} },         
};

SR__ s_90[] =
{
    { { REQ_DEF}, {   6} },         
    { {     265}, {  55} }, // PLUS 
    { {     266}, {  56} }, // MINUS
    { {     267}, {  57} }, // MUL  
    { {     268}, {  58} }, // DIV  
    { {     269}, {  59} }, // MOD  
    { {       0}, { -47} },         
};

SR__ s_91[] =
{
    { { REQ_DEF}, {   6} },         
    { {     265}, {  55} }, // PLUS 
    { {     266}, {  56} }, // MINUS
    { {     267}, {  57} }, // MUL  
    { {     268}, {  58} }, // DIV  
    { {     269}, {  59} }, // MOD  
    { {       0}, { -48} },         
};

SR__ s_92[] =
{
    { { REQ_DEF}, {   6} },         
    { {     265}, {  55} }, // PLUS 
    { {     266}, {  56} }, // MINUS
    { {     267}, {  57} }, // MUL  
    { {     268}, {  58} }, // DIV  
    { {     269}, {  59} }, // MOD  
    { {       0}, { -49} },         
};

SR__ s_93[] =
{
    { { REQ_DEF}, {  12} },                 
    { {     265}, {  55} }, // PLUS         
    { {     266}, {  56} }, // MINUS        
    { {     267}, {  57} }, // MUL          
    { {     268}, {  58} }, // DIV          
    { {     269}, {  59} }, // MOD          
    { {     259}, {  60} }, // EQUAL        
    { {     260}, {  61} }, // NOT_EQUAL    
    { {     261}, {  62} }, // LESS         
    { {     263}, {  63} }, // LESS_EQUAL   
    { {     262}, {  64} }, // GREATER      
    { {     264}, {  65} }, // GREATER_EQUAL
    { {       0}, { -50} },                 
};

SR__ s_94[] =
{
    { { REQ_DEF}, {  12} },                 
    { {     265}, {  55} }, // PLUS         
    { {     266}, {  56} }, // MINUS        
    { {     267}, {  57} }, // MUL          
    { {     268}, {  58} }, // DIV          
    { {     269}, {  59} }, // MOD          
    { {     259}, {  60} }, // EQUAL        
    { {     260}, {  61} }, // NOT_EQUAL    
    { {     261}, {  62} }, // LESS         
    { {     263}, {  63} }, // LESS_EQUAL   
    { {     262}, {  64} }, // GREATER      
    { {     264}, {  65} }, // GREATER_EQUAL
    { {       0}, { -51} },                 
};

SR__ s_95[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_96[] =
{
    { { REQ_TOKEN}, {  15} },                 
    { {       272}, { 104} }, // CLOSE        
    { {       265}, {  55} }, // PLUS         
    { {       266}, {  56} }, // MINUS        
    { {       267}, {  57} }, // MUL          
    { {       268}, {  58} }, // DIV          
    { {       269}, {  59} }, // MOD          
    { {       259}, {  60} }, // EQUAL        
    { {       260}, {  61} }, // NOT_EQUAL    
    { {       261}, {  62} }, // LESS         
    { {       263}, {  63} }, // LESS_EQUAL   
    { {       262}, {  64} }, // GREATER      
    { {       264}, {  65} }, // GREATER_EQUAL
    { {       257}, {  66} }, // AND          
    { {       258}, {  67} }, // OR           
    { {         0}, {   0} },                 
};

SR__ s_97[] =
{
    { { REQ_TOKEN}, {  15} },                 
    { {       272}, { 105} }, // CLOSE        
    { {       265}, {  55} }, // PLUS         
    { {       266}, {  56} }, // MINUS        
    { {       267}, {  57} }, // MUL          
    { {       268}, {  58} }, // DIV          
    { {       269}, {  59} }, // MOD          
    { {       259}, {  60} }, // EQUAL        
    { {       260}, {  61} }, // NOT_EQUAL    
    { {       261}, {  62} }, // LESS         
    { {       263}, {  63} }, // LESS_EQUAL   
    { {       262}, {  64} }, // GREATER      
    { {       264}, {  65} }, // GREATER_EQUAL
    { {       257}, {  66} }, // AND          
    { {       258}, {  67} }, // OR           
    { {         0}, {   0} },                 
};

SR__ s_98[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR__ s_99[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_100[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_101[] =
{
    { { REQ_TOKEN}, {   8} },              
    { {       332}, { 106} }, // expr      
    { {       282}, {  42} }, // FALSE     
    { {       281}, {  43} }, // TRUE      
    { {       292}, {  44} }, // NUMBER    
    { {       280}, {  69} }, // IDENTIFIER
    { {       270}, {  45} }, // NEGATE    
    { {       271}, {  46} }, // OPEN      
    { {         0}, {   0} },              
};

SR__ s_102[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_103[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_104[] =
{
    { { REQ_TOKEN}, {   2} },         
    { {       276}, { 107} }, // BOPEN
    { {         0}, {   0} },         
};

SR__ s_105[] =
{
    { { REQ_TOKEN}, {   2} },         
    { {       276}, { 108} }, // BOPEN
    { {         0}, {   0} },         
};

SR__ s_106[] =
{
    { { REQ_DEF}, {  14} },                 
    { {     265}, {  55} }, // PLUS         
    { {     266}, {  56} }, // MINUS        
    { {     267}, {  57} }, // MUL          
    { {     268}, {  58} }, // DIV          
    { {     269}, {  59} }, // MOD          
    { {     259}, {  60} }, // EQUAL        
    { {     260}, {  61} }, // NOT_EQUAL    
    { {     261}, {  62} }, // LESS         
    { {     263}, {  63} }, // LESS_EQUAL   
    { {     262}, {  64} }, // GREATER      
    { {     264}, {  65} }, // GREATER_EQUAL
    { {     257}, {  66} }, // AND          
    { {     258}, {  67} }, // OR           
    { {       0}, { -57} },                 
};

SR__ s_107[] =
{
    { { REQ_DEF}, {  24} },                 
    { {     322}, { 109} }, // statements   
    { {     323}, {  25} }, // statement    
    { {     324}, {  26} }, // assignment   
    { {     325}, {  27} }, // read         
    { {     326}, {  28} }, // write        
    { {     327}, {  29} }, // exprStatement
    { {     328}, {  30} }, // return       
    { {     329}, {  31} }, // break        
    { {     330}, {  32} }, // if           
    { {     331}, {  33} }, // while        
    { {     280}, {  34} }, // IDENTIFIER   
    { {     287}, {  35} }, // CIN          
    { {     286}, {  36} }, // COUT         
    { {     332}, {  37} }, // expr         
    { {     288}, {  38} }, // RETURN       
    { {     289}, {  39} }, // BREAK        
    { {     283}, {  40} }, // IF           
    { {     285}, {  41} }, // WHILE        
    { {     282}, {  42} }, // FALSE        
    { {     281}, {  43} }, // TRUE         
    { {     292}, {  44} }, // NUMBER       
    { {     270}, {  45} }, // NEGATE       
    { {     271}, {  46} }, // OPEN         
    { {       0}, { -15} },                 
};

SR__ s_108[] =
{
    { { REQ_DEF}, {  24} },                 
    { {     322}, { 110} }, // statements   
    { {     323}, {  25} }, // statement    
    { {     324}, {  26} }, // assignment   
    { {     325}, {  27} }, // read         
    { {     326}, {  28} }, // write        
    { {     327}, {  29} }, // exprStatement
    { {     328}, {  30} }, // return       
    { {     329}, {  31} }, // break        
    { {     330}, {  32} }, // if           
    { {     331}, {  33} }, // while        
    { {     280}, {  34} }, // IDENTIFIER   
    { {     287}, {  35} }, // CIN          
    { {     286}, {  36} }, // COUT         
    { {     332}, {  37} }, // expr         
    { {     288}, {  38} }, // RETURN       
    { {     289}, {  39} }, // BREAK        
    { {     283}, {  40} }, // IF           
    { {     285}, {  41} }, // WHILE        
    { {     282}, {  42} }, // FALSE        
    { {     281}, {  43} }, // TRUE         
    { {     292}, {  44} }, // NUMBER       
    { {     270}, {  45} }, // NEGATE       
    { {     271}, {  46} }, // OPEN         
    { {       0}, { -15} },                 
};

SR__ s_109[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       277}, { 111} }, // BCLOSE
    { {         0}, {   0} },          
};

SR__ s_110[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       277}, { 112} }, // BCLOSE
    { {         0}, {   0} },          
};

SR__ s_111[] =
{
    { { REQ_DEF}, {   2} },        
    { {     284}, { 113} }, // ELSE
    { {       0}, { -32} },        
};

SR__ s_112[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_113[] =
{
    { { REQ_TOKEN}, {   2} },         
    { {       276}, { 114} }, // BOPEN
    { {         0}, {   0} },         
};

SR__ s_114[] =
{
    { { REQ_DEF}, {  24} },                 
    { {     322}, { 115} }, // statements   
    { {     323}, {  25} }, // statement    
    { {     324}, {  26} }, // assignment   
    { {     325}, {  27} }, // read         
    { {     326}, {  28} }, // write        
    { {     327}, {  29} }, // exprStatement
    { {     328}, {  30} }, // return       
    { {     329}, {  31} }, // break        
    { {     330}, {  32} }, // if           
    { {     331}, {  33} }, // while        
    { {     280}, {  34} }, // IDENTIFIER   
    { {     287}, {  35} }, // CIN          
    { {     286}, {  36} }, // COUT         
    { {     332}, {  37} }, // expr         
    { {     288}, {  38} }, // RETURN       
    { {     289}, {  39} }, // BREAK        
    { {     283}, {  40} }, // IF           
    { {     285}, {  41} }, // WHILE        
    { {     282}, {  42} }, // FALSE        
    { {     281}, {  43} }, // TRUE         
    { {     292}, {  44} }, // NUMBER       
    { {     270}, {  45} }, // NEGATE       
    { {     271}, {  46} }, // OPEN         
    { {       0}, { -15} },                 
};

SR__ s_115[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       277}, { 116} }, // BCLOSE
    { {         0}, {   0} },          
};

SR__ s_116[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
        // $insert LTYPEresize
        d_locationStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
    // $insert LTYPEpush
    *(d_lsp__ = &d_locationStack__[d_stackIdx__]) = d_loc__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
    // $insert LTYPEpop
    d_lsp__ = &d_locationStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

// $insert defaultactionreturn
                            // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 45 "blang.y"
        { m_globalScope = d_vsp__[0].classtype; }
        break;

        case 2:
#line 52 "blang.y"
        { d_val__.classtype = new Class(); std::cout << "new class " << d_val__.classtype << std::endl; }
        break;

        case 3:
#line 54 "blang.y"
        { d_val__.classtype = d_vsp__[0].classtype; d_val__.classtype->AddFunction(d_vsp__[-1].function); }
        break;

        case 4:
#line 56 "blang.y"
        { d_val__.classtype = d_vsp__[0].classtype; d_val__.classtype->AddVariable(d_vsp__[-2].declaration); }
        break;

        case 5:
#line 63 "blang.y"
        {
         d_val__.function = new Function{d_vsp__[-7].stringvalue, d_vsp__[-8].type, d_vsp__[-5].declaration, d_vsp__[-2].declaration, d_vsp__[-1].statement};
         }
        break;

        case 6:
#line 69 "blang.y"
        { d_val__.declaration = nullptr; }
        break;

        case 7:
#line 71 "blang.y"
        { d_val__.declaration = d_vsp__[0].declaration; }
        break;

        case 8:
#line 75 "blang.y"
        { d_val__.declaration = d_vsp__[0].declaration; }
        break;

        case 9:
#line 78 "blang.y"
        {
         d_val__.declaration = d_vsp__[-2].declaration;
         d_val__.declaration->next = d_vsp__[0].declaration;
         d_loc__ = Location::Between(d_lsp__[-2], d_lsp__[0]);
         }
        break;

        case 10:
#line 86 "blang.y"
        { d_val__.declaration = nullptr; }
        break;

        case 11:
#line 89 "blang.y"
        {
         d_val__.declaration = d_vsp__[-2].declaration;
         d_val__.declaration->next = d_vsp__[0].declaration;
         d_loc__ = Location::Between(d_lsp__[-2], d_lsp__[0]);
         }
        break;

        case 12:
#line 97 "blang.y"
        {
         d_val__.declaration = new Declaration;
         d_val__.declaration->type = d_vsp__[-1].type;
         d_val__.declaration->name = d_vsp__[0].stringvalue;
         d_loc__ = Location::Between(d_lsp__[-1], d_lsp__[0]);
         }
        break;

        case 15:
#line 108 "blang.y"
        { d_val__.statement = nullptr; }
        break;

        case 16:
#line 110 "blang.y"
        { d_val__.statement = d_vsp__[-1].statement; d_val__.statement->next = d_vsp__[0].statement; }
        break;

        case 25:
#line 133 "blang.y"
        {
         d_val__.statement = new AssignmentStatement(d_vsp__[-3].stringvalue, d_vsp__[-1].expr);
         d_loc__ = d_val__.statement->location = Location::Between(d_lsp__[-3], d_lsp__[0]);
         }
        break;

        case 26:
#line 140 "blang.y"
        {
         d_val__.statement = new ReadStatement(d_vsp__[-1].stringvalue);
         d_loc__ = d_val__.statement->location = Location::Between(d_lsp__[-3], d_lsp__[0]);
         }
        break;

        case 27:
#line 147 "blang.y"
        {
         d_val__.statement = new WriteStatement(d_vsp__[-1].expr);
         d_loc__ = d_val__.statement->location = Location::Between(d_lsp__[-3], d_lsp__[0]);
         }
        break;

        case 28:
#line 154 "blang.y"
        {
         d_val__.statement = new ExprStatement(d_vsp__[-1].expr);
         d_loc__ = d_val__.statement->location = Location::Between(d_lsp__[-1], d_lsp__[0]);
         }
        break;

        case 29:
#line 161 "blang.y"
        {
         d_val__.statement = new ReturnStatement(d_vsp__[-1].expr);
         d_loc__ = d_val__.statement->location = Location::Between(d_lsp__[-2], d_lsp__[0]);
         }
        break;

        case 30:
#line 168 "blang.y"
        {
         d_val__.statement = new BreakStatement;
         d_loc__ = d_val__.statement->location = Location::Between(d_lsp__[-1], d_lsp__[0]);
         }
        break;

        case 31:
#line 176 "blang.y"
        {
         d_val__.statement = new IfStatement(d_vsp__[-8].expr, d_vsp__[-5].statement, d_vsp__[-1].statement);
         d_loc__ = d_val__.statement->location = Location::Between(d_lsp__[-10], d_lsp__[0]);
         }
        break;

        case 32:
#line 182 "blang.y"
        {
         d_val__.statement = new IfStatement(d_vsp__[-4].expr, d_vsp__[-1].statement, nullptr);
         d_loc__ = d_val__.statement->location = Location::Between(d_lsp__[-6], d_lsp__[0]);
         }
        break;

        case 33:
#line 189 "blang.y"
        {
         d_val__.statement = new WhileStatement(d_vsp__[-4].expr, d_vsp__[-1].statement);
         d_loc__ = d_val__.statement->location = Location::Between(d_lsp__[-6], d_lsp__[0]);
         }
        break;

        case 34:
#line 196 "blang.y"
        {
         d_loc__ = d_lsp__[0];
         d_val__.expr = new Expression(d_loc__, ExprType::VALUE);
         d_val__.expr->value = false;
         }
        break;

        case 35:
#line 202 "blang.y"
        {
         d_loc__ = d_lsp__[0];
         d_val__.expr = new Expression(d_loc__, ExprType::VALUE);
         d_val__.expr->value = true;
         }
        break;

        case 36:
#line 208 "blang.y"
        {
         d_loc__ = d_lsp__[0];
         d_val__.expr = new Expression(d_loc__, ExprType::VALUE);
         d_val__.expr->value = d_vsp__[0].intvalue;
         }
        break;

        case 37:
#line 214 "blang.y"
        {
         d_loc__ = Location::Between(d_lsp__[-3], d_lsp__[0]);
         d_val__.expr = new Expression(d_loc__, ExprType::CALL, *d_vsp__[-1].exprlist);
         d_val__.expr->name = d_vsp__[-3].stringvalue;
         delete d_vsp__[-1].exprlist;
         }
        break;

        case 38:
#line 222 "blang.y"
        {
         d_loc__ = d_lsp__[0];
         d_val__.expr = new Expression(d_loc__, ExprType::IDENTIFIER);
         d_val__.expr->name = d_vsp__[0].stringvalue;
         
        
         }
        break;

        case 39:
#line 231 "blang.y"
        { d_loc__ = Location::Between(d_lsp__[-2], d_lsp__[0]); d_val__.expr = new Expression(d_loc__, ExprType::PLUS, { d_vsp__[-2].expr, d_vsp__[0].expr }); }
        break;

        case 40:
#line 233 "blang.y"
        { d_loc__ = Location::Between(d_lsp__[-2], d_lsp__[0]); d_val__.expr = new Expression(d_loc__, ExprType::MINUS, { d_vsp__[-2].expr, d_vsp__[0].expr }); }
        break;

        case 41:
#line 235 "blang.y"
        { d_loc__ = Location::Between(d_lsp__[-2], d_lsp__[0]); d_val__.expr = new Expression(d_loc__, ExprType::MUL, { d_vsp__[-2].expr, d_vsp__[0].expr }); }
        break;

        case 42:
#line 237 "blang.y"
        { d_loc__ = Location::Between(d_lsp__[-2], d_lsp__[0]); d_val__.expr = new Expression(d_loc__, ExprType::DIV, { d_vsp__[-2].expr, d_vsp__[0].expr }); }
        break;

        case 43:
#line 239 "blang.y"
        { d_loc__ = Location::Between(d_lsp__[-2], d_lsp__[0]); d_val__.expr = new Expression(d_loc__, ExprType::MOD, { d_vsp__[-2].expr, d_vsp__[0].expr }); }
        break;

        case 44:
#line 241 "blang.y"
        { d_loc__ = Location::Between(d_lsp__[-2], d_lsp__[0]); d_val__.expr = new Expression(d_loc__, ExprType::EQUAL, { d_vsp__[-2].expr, d_vsp__[0].expr }); }
        break;

        case 45:
#line 243 "blang.y"
        { d_loc__ = Location::Between(d_lsp__[-2], d_lsp__[0]); d_val__.expr = new Expression(d_loc__, ExprType::NOT_EQUAL, { d_vsp__[-2].expr, d_vsp__[0].expr }); }
        break;

        case 46:
#line 245 "blang.y"
        { d_loc__ = Location::Between(d_lsp__[-2], d_lsp__[0]); d_val__.expr = new Expression(d_loc__, ExprType::LESS, { d_vsp__[-2].expr, d_vsp__[0].expr }); }
        break;

        case 47:
#line 247 "blang.y"
        { d_loc__ = Location::Between(d_lsp__[-2], d_lsp__[0]); d_val__.expr = new Expression(d_loc__, ExprType::LESS_EQUAL, { d_vsp__[-2].expr, d_vsp__[0].expr }); }
        break;

        case 48:
#line 249 "blang.y"
        { d_loc__ = Location::Between(d_lsp__[-2], d_lsp__[0]); d_val__.expr = new Expression(d_loc__, ExprType::GREATER, { d_vsp__[-2].expr, d_vsp__[0].expr }); }
        break;

        case 49:
#line 251 "blang.y"
        { d_loc__ = Location::Between(d_lsp__[-2], d_lsp__[0]); d_val__.expr = new Expression(d_loc__, ExprType::GREATER_EQUAL, { d_vsp__[-2].expr, d_vsp__[0].expr }); }
        break;

        case 50:
#line 253 "blang.y"
        { d_loc__ = Location::Between(d_lsp__[-2], d_lsp__[0]); d_val__.expr = new Expression(d_loc__, ExprType::AND, { d_vsp__[-2].expr, d_vsp__[0].expr }); }
        break;

        case 51:
#line 255 "blang.y"
        { d_loc__ = Location::Between(d_lsp__[-2], d_lsp__[0]); d_val__.expr = new Expression(d_loc__, ExprType::OR, { d_vsp__[-2].expr, d_vsp__[0].expr });; }
        break;

        case 52:
#line 257 "blang.y"
        { d_loc__ = Location::Between(d_lsp__[-1], d_lsp__[0]); d_val__.expr = new Expression(d_loc__, ExprType::NEGATE, { d_vsp__[0].expr }); }
        break;

        case 53:
#line 259 "blang.y"
        { d_loc__ = Location::Between(d_lsp__[-2], d_lsp__[0]); d_val__.expr = d_vsp__[-1].expr; d_val__.expr->location = d_loc__; }
        break;

        case 54:
#line 263 "blang.y"
        {
         d_val__.exprlist = new std::vector<Expression*>;
         }
        break;

        case 55:
#line 268 "blang.y"
        {
         d_val__.exprlist = new std::vector<Expression*>;
         }
        break;

        case 56:
#line 275 "blang.y"
        {
         d_val__.exprlist = new std::vector<Expression*>;
         d_val__.exprlist->push_back(d_vsp__[0].expr);
         }
        break;

        case 57:
#line 281 "blang.y"
        {
         d_val__.exprlist = d_vsp__[-2].exprlist;
         d_val__.exprlist->push_back(d_vsp__[0].expr);
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



