// Generated by Bisonc++ V4.13.01 on Thu, 27 Sep 2018 00:57:24 +0200

#ifndef Parser_h_included
#define Parser_h_included

// $insert baseclass
#include <FlexLexer.h>
#include "Types.h"
#include "Parserbase.h"

#undef Parser

#include "Lexer.h"
#include "Source.h"

class Parser : public ParserBase
{

public:
	Parser(Source &source) : lexer(&source.Stream(), &std::cerr), m_source(source) {}
	int parse();

	Class *GetGlobalScope() { return m_globalScope; }

private:
	Lexer lexer;
	void error(char const *msg);    // called on (syntax) errors
	int lex();                      // returns the next token from the
									// lexical scanner. 
	void print();                   // use, e.g., d_token, d_loc

// support functions for parse():
	void executeAction(int ruleNr);
	void errorRecovery();
	int lookup(bool recovery);
	void nextToken();
	void print__();
	void exceptionHandler__(std::exception const &exc);

	Source &m_source;
	Class *m_globalScope = nullptr;
};

#endif
